### ISSUE TITLE
Can't get fields from embeddable entity by fetch plan

### ISSUE THREAD

**Issue by HegelPro** [Haulmont/jmix-rest#53]
### Request
Get entity with embedded field by  fetch plan:

![jmix-emb-bug-request-querys](https://user-images.githubusercontent.com/34520941/111174390-d34a2980-85c0-11eb-99c5-3c72813ef474.png)

Fetch Plan:

![jmix-emb-bug-fetch-plan](https://user-images.githubusercontent.com/34520941/111174465-e2c97280-85c0-11eb-80a7-f724530e3dcd.png)

### Response
![jmix-emb-bug-response](https://user-images.githubusercontent.com/34520941/111174573-f83e9c80-85c0-11eb-86fc-6c845d417eb2.png)

**Comment by plakhov** [comment]
In the [project](https://github.com/jmix-projects/scr-jmix/tree/vb/chore%2Fadd-embedded-entity-to-model) where the bug is reproducing field `name` doesn't have `@Column` annotation. But the annotation is mandatory for any fields in an entity. 

The entity should look like
```
@Embeddable
@JmixEntity(name = "scr_EmbeddableTestEntity")
public class EmbeddableTestEntity {
    @Column
    private String name;
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
}
```

The best way for adding fields into entities is using Jmix Studio entity designer
