### ISSUE TITLE
Can't save date time format

### ISSUE THREAD

**Issue by HegelPro** [Haulmont/jmix-rest#65]
![request](https://user-images.githubusercontent.com/34520941/113690125-2143e000-96dc-11eb-8763-74c137344ac6.png)

## Field type:
![field type](https://user-images.githubusercontent.com/34520941/113691528-906e0400-96dd-11eb-9fe5-17f303a625d6.png)

The bug has been found here [previous issue](https://github.com/Haulmont/jmix-frontend/issues/142)

**Comment by plakhov** [comment]
The root cause the issues same as https://app.zenhub.com/workspaces/jmix-5c76946ebe8f221bc5019e22/issues/haulmont/jmix-core/89
Attribute `timeAttr ` has wrong type java.sql.Time if we want to create an attribute with time type we should use the following construction
@Temporal(TemporalType.TIME)
@Column(name = "TIME_ATRRRRR")
private Date timeAttr;

During the investigation problem, I found another bug - https://app.zenhub.com/workspaces/jmix-5c76946ebe8f221bc5019e22/issues/haulmont/jmix-core/135
