### ISSUE TITLE
Can't expose service method if bean doesn't implement interfaces

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-rest#68]
Need to check, haven't tested personally.

But io.jmix.rest.api.config.RestServicesConfiguration#_findMethod method
has the logic (inherited from CUBA): that service bean must implement at least one interface, and exposed method must be present in one of those interfaces.

Need to rewise this logic for Jmix. It is still necessary?

**Comment by mariodavid** [comment]
I had a brief discussion with @knstvk and just repost the comment here:

What I see from the code are the following requirements for a class to be able to be used as part of the Services API:
* It needs to be a Spring bean
* It needs to implement at least one interface (see [RestServicesConfiguration](https://github.com/Haulmont/jmix-rest/blob/master/rest/src/main/java/io/jmix/rest/impl/config/RestServicesConfiguration.java#L196))

What I did not find is that it is needed to annotate it as @Service.

From the Spring docu, the annotation does not have specific meaning for Spring itself, but it is possible to use that for dedicated other mechanisms (like the Jmix service API):
> Therefore, you can annotate your component classes with @Component, but, by annotating them with @Repository, @Service, or @Controller instead, your classes are more properly suited for processing by tools or associating with aspects.

Source: Spring [docs](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-stereotype-annotations).

Would it make sense, that if a REST service needs an interface and is conceptually called service that it also would need to be annotated with @Service? Then at least it is concise with the terminology.

If the necessity goes away to have an interface at all because it is not needed anymore, probably this restriction is also less valuable.

**Comment by knstvk** [comment]
Decided to enable exposing only beans annotated with `@Service`. Interface is not needed.
